name: iride_template
channels:
  - conda-forge
dependencies:
  - cartopy
  - gdal
  - matplotlib
  - numpy
  - pip
  - pyproj
  - pyyaml
  - scipy
  - setuptools_scm
  - pandas
  - geopandas
  - shapely
  - flake8
  - pytest
  - pytest-cov
  - codecov
  - coverage